apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: devtrack

spec:
  replicas: 3


  strategy:
    type: RollingUpdate
  
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
        component: api

    spec:
      serviceAccountName: backend-sa
      priorityClassName: backend-high-priority

      

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - backend

        podAntiAffinity: # <-- affinity ke theek neeche, 8 spaces par
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm: # <-- iske andar baqi dono fields aayengi
              topologyKey: kubernetes.io/hostname # <-- 14 spaces par
              labelSelector: # <-- 14 spaces par
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - backend


      containers:
        - name: backend

          image: nasirhayat028/devtrack-backend:98e5d8e2a91370e3edeb1c4251c084308a03d659

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: devtrack-config

            - secretRef:
                name: devtrack-secret

          startupProbe:
            httpGet: 
              path: /api/health
              port: 5000

            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000

            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3


          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000

            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 1
            failureThreshold: 3


          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"
