sonar.projectKey=devtrack-devsecops
sonar.projectName=DevTrack DevSecOps

sonar.sources=backend/src,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.sourceEncoding=UTF-8