apiVersion: v1
kind: Secret

metadata:
  name: devtrack-secret
  namespace: devtrack

type: Opaque

stringData:
  JWT_SECRET: change_this_to_a_long_random_secret

  MONGO_USERNAME: admin
  MONGO_PASSWORD: admin123

  # MONGO_URI: mongodb://admin:admin123@mongodb:27017/devtrack?authSource=admin


  # MONGO_URI: "mongodb://admin:admin123@mongodb:27017/devtrack?authSource=admin"
  #Production String (StatefulSet Pod standard):
  MONGO_URI: mongodb://admin:admin123@mongodb-0.mongodb-headless.devtrack.svc.cluster.local:27017/devtrack?authSource=admin
