name: DevTrack First Workflow

on: 
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Starting DevTrack CI"

      - name: Step 2
        run: echo "Pipeline Finished" 